version: '3.8'
services:
  paxfax-dev:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file: .env
    environment:
      - NODE_ENV=development
    command: npm run dev